/**
 * This implementation is based on https://github.com/antontutoveanu/crystals-kyber-javascript,
 * which was deveploped under the MIT licence below:
 * https://github.com/antontutoveanu/crystals-kyber-javascript/blob/main/LICENSE
 */
import { N } from "./consts.ts";
import { MlKemError } from "./errors.ts";
import { MlKemBase } from "./mlKemBase.ts";

/**
 * Represents the MlKem768 class, which extends the MlKemBase class.
 *
 * This class extends the MlKemBase class and provides specific implementation for MlKem768.
 *
 * @remarks
 *
 * MlKem768 is a specific implementation of the ML-KEM key encapsulation mechanism.
 *
 * @example
 *
 * ```ts
 * // Using jsr:
 * import { MlKem768 } from "@dajiaji/mlkem";
 * // Using npm:
 * // import { MlKem768 } from "mlkem"; // or "crystals-kyber-js"
 *
 * const recipient = new MlKem768();
 * const [pkR, skR] = await recipient.generateKeyPair();
 *
 * const sender = new MlKem768();
 * const [ct, ssS] = await sender.encap(pkR);
 *
 * const ssR = await recipient.decap(ct, skR);
 * // ssS === ssR
 * ```
 */
export class MlKem768 extends MlKemBase {
  override _k = 3;
  override _du = 10;
  override _dv = 4;
  override _eta1 = 2;
  override _eta2 = 2;

  constructor() {
    super();
    this._skSize = 12 * this._k * N / 8;
    this._pkSize = this._skSize + 32;
    this._compressedUSize = this._k * this._du * N / 8;
    this._compressedVSize = this._dv * N / 8;
  }

  /**
   * Generates a keypair [publicKey, privateKey].
   *
   * If an error occurred, throws {@link MlKemError}.
   *
   * @returns A kaypair [publicKey, privateKey].
   * @throws {@link MlKemError}
   */
  public async generateKeyPair(): Promise<[Uint8Array, Uint8Array]> {
    await this._setup();
    try {
      return this._generateKeyPairCore();
    } catch (e: unknown) {
      throw new MlKemError(e);
    }
  }

  /**
   * Derives a keypair [publicKey, privateKey] deterministically from a 64-octet seed.
   *
   * If an error occurred, throws {@link MlKemError}.
   *
   * @param seed A 64-octet seed for the deterministic key generation.
   * @returns A kaypair [publicKey, privateKey].
   * @throws {@link MlKemError}
   */
  public async deriveKeyPair(
    seed: Uint8Array,
  ): Promise<[Uint8Array, Uint8Array]> {
    await this._setup();
    try {
      return this._deriveKeyPairCore(seed);
    } catch (e: unknown) {
      throw new MlKemError(e);
    }
  }

  /**
   * Generates a shared secret from the encapsulated ciphertext and the private key.
   *
   * If an error occurred, throws {@link MlKemError}.
   *
   * @param pk A public key.
   * @param seed An optional 32-octet seed for the deterministic shared secret generation.
   * @returns A ciphertext (encapsulated public key) and a shared secret.
   * @throws {@link MlKemError}
   */
  public async encap(
    pk: Uint8Array,
    seed?: Uint8Array,
  ): Promise<[Uint8Array, Uint8Array]> {
    await this._setup();
    try {
      return this._encapCore(pk, seed);
    } catch (e: unknown) {
      throw new MlKemError(e);
    }
  }

  /**
   * Generates a ciphertext for the public key and a shared secret.
   *
   * If an error occurred, throws {@link MlKemError}.
   *
   * @param ct A ciphertext generated by {@link encap}.
   * @param sk A private key.
   * @returns A shared secret.
   * @throws {@link MlKemError}
   */
  public async decap(ct: Uint8Array, sk: Uint8Array): Promise<Uint8Array> {
    await this._setup();
    try {
      return this._decapCore(ct, sk);
    } catch (e: unknown) {
      throw new MlKemError(e);
    }
  }
}
